const $=s=>document.querySelector(s);
const fallback=[1,2,3,4,5].map(n=>({id:"demo-"+n,name:"CUTDOWN TEE 0"+n,price:0,image_url:"assets/t shirt cutdown.jpeg",stock:0,active:true}));
const state={products:[],cart:JSON.parse(localStorage.getItem("cutdown_cart")||"[]")};
function money(v){return "EGP "+Number(v||0).toLocaleString("en-EG",{maximumFractionDigits:2})}
function save(){localStorage.setItem("cutdown_cart",JSON.stringify(state.cart));renderCart()}
function renderProducts(){const el=$("#products");el.innerHTML=state.products.map((p,i)=>'<article class="product"><img src="'+(p.image_url||"assets/t shirt cutdown.jpeg")+'" alt="'+p.name+'"><div class="product-info"><span>0'+(i+1)+'</span><h3>'+p.name+'</h3><p>'+money(p.price)+'</p><button data-add="'+p.id+'">Add to bag</button></div></article>').join("");el.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>{const id=b.dataset.add,found=state.cart.find(x=>x.product_id===id);if(found)found.quantity++;else state.cart.push({product_id:id,quantity:1});save();openCart()})}
function renderCart(){const el=$("#cartItems");$("#cartCount").textContent=state.cart.reduce((n,x)=>n+x.quantity,0);let total=0;el.innerHTML=state.cart.map(x=>{const p=state.products.find(y=>y.id===x.product_id);if(!p)return "";total+=Number(p.price)*x.quantity;return '<div class="cart-item"><span>'+p.name+" × "+x.quantity+'</span><b>'+money(Number(p.price)*x.quantity)+'</b></div>'}).join("")||'<p style="color:#777">Your bag is empty.</p>';$("#cartTotal").textContent=money(total)}
function openCart(){$("#cart").classList.add("open")}function closeCart(){$("#cart").classList.remove("open")}
$("#cartBtn").onclick=openCart;$("#closeCart").onclick=closeCart;$("#checkoutBtn").onclick=()=>{if(!state.cart.length)return;closeCart();$("#checkout").classList.add("open")};$("#closeCheckout").onclick=()=>$("#checkout").classList.remove("open");
async function loadReviews(){try{const r=await fetch("/api/reviews");if(!r.ok)throw 0;const data=await r.json();$("#reviewList").innerHTML=data.length?data.map(x=>'<article class="review"><div class="stars">'+("★".repeat(x.rating))+'</div><h3>'+String(x.name).replace(/[<>]/g,"")+'</h3><p>'+String(x.body).replace(/[<>]/g,"")+'</p></article>').join(""):'<p>No reviews yet. Be the first.</p>'}catch{$("#reviewList").innerHTML='<p>Reviews will appear here once Supabase is connected.</p>'}}
$("#reviewForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch("/api/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(f))}),d=await r.json();if(!r.ok)return alert(d.error||"Could not post review");e.currentTarget.reset();loadReviews()};
$("#checkoutForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),customer=Object.fromEntries(f),payment_method=customer.payment_method;delete customer.payment_method;const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer,items:state.cart,payment_method})}),d=await r.json();const msg=$("#checkoutMsg");if(!r.ok){msg.textContent=d.error||"Checkout failed.";return}if(payment_method==="online"&&d.checkout_url){window.location.href=d.checkout_url;return}state.cart=[];save();e.currentTarget.reset();msg.textContent=d.message||"Order confirmed."};
let pointer={x:0,y:0},scrollYValue=0;
function updateHero(){const m=$("#model"),hero=document.querySelector(".hero");if(!m||!hero)return;const p=Math.min(1,Math.max(0,scrollYValue/(hero.offsetHeight*.95)));const depth=-320-p*900,scale=1.15-p*.5,opacity=1-p;const x=-pointer.x*34,y=-pointer.y*24-p*110; m.style.opacity=String(opacity);m.style.transform="translate3d("+x+"px,"+y+"px,"+depth+"px) scale("+scale+") rotateY("+(-pointer.x*3)+"deg) rotateX("+(pointer.y*2)+"deg)")}
addEventListener("pointermove",e=>{pointer.x=(e.clientX-innerWidth/2)/innerWidth;pointer.y=(e.clientY-innerHeight/2)/innerHeight;updateHero()});
addEventListener("scroll",()=>{scrollYValue=scrollY;updateHero()},{passive:true});
(async()=>{try{const r=await fetch("/api/products");if(!r.ok)throw 0;const data=await r.json();state.products=Array.isArray(data)&&data.length?data:fallback}catch{state.products=fallback}renderProducts();renderCart();await loadReviews();document.body.classList.add("ready");updateHero()})();