const $=s=>document.querySelector(s);
const state={products:[],cart:JSON.parse(localStorage.getItem("cutdown_cart")||"[]")};
function money(v){return "EGP "+Number(v||0).toLocaleString("en-EG",{minimumFractionDigits:0,maximumFractionDigits:2})}
function save(){localStorage.setItem("cutdown_cart",JSON.stringify(state.cart));renderCart()}
function renderProducts(){const el=$("#products");el.innerHTML=state.products.map((p,i)=>'<article class="product"><img src="'+(p.image_url||"assets/t shirt cutdown.jpeg")+'" alt="'+p.name+'"><div class="product-info"><span>0'+(i+1)+'</span><h3>'+p.name+'</h3><p>'+money(p.price)+'</p><button data-add="'+p.id+'">Add to bag</button></div></article>').join("");el.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>{const id=b.dataset.add;const found=state.cart.find(x=>x.product_id===id);if(found)found.quantity++;else state.cart.push({product_id:id,quantity:1});save();openCart()})}
function renderCart(){const el=$("#cartItems");$("#cartCount").textContent=state.cart.reduce((n,x)=>n+x.quantity,0);let total=0;el.innerHTML=state.cart.map(x=>{const p=state.products.find(y=>y.id===x.product_id);if(!p)return "";total+=Number(p.price)*x.quantity;return '<div class="cart-item"><span>'+p.name+' × '+x.quantity+'</span><b>'+money(Number(p.price)*x.quantity)+'</b></div>'}).join("")||'<p style="color:#777">Your bag is empty.</p>';$("#cartTotal").textContent=money(total)}
function openCart(){$("#cart").classList.add("open")}function closeCart(){$("#cart").classList.remove("open")}
$("#cartBtn").onclick=openCart;$("#closeCart").onclick=closeCart;
$("#checkoutBtn").onclick=()=>{if(!state.cart.length)return;closeCart();$("#checkout").classList.add("open")};$("#closeCheckout").onclick=()=>$("#checkout").classList.remove("open");
$("#reviewForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});const d=await r.json();if(!r.ok)return alert(d.error||"Could not post review");e.currentTarget.reset();loadReviews()};
async function loadReviews(){const r=await fetch("/api/reviews");if(!r.ok)return;const data=await r.json();$("#reviewList").innerHTML=data.length?data.map(x=>'<article class="review"><div class="stars">'+("★".repeat(x.rating))+'</div><h3>'+x.name.replace(/[<>]/g,"")+'</h3><p>'+x.body.replace(/[<>]/g,"")+'</p></article>').join(""):'<p>No reviews yet. Be the first.</p>'}
$("#checkoutForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const customer=Object.fromEntries(f);const payment_method=customer.payment_method;delete customer.payment_method;const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer,items:state.cart,payment_method})});const d=await r.json();const msg=$("#checkoutMsg");msg.textContent=d.error||d.message;if(!r.ok)return;if(payment_method==="online"){msg.textContent="Order created as pending payment. Connect the Paymob credentials to launch the verified payment screen.";return}state.cart=[];save();e.currentTarget.reset()};
let pointer={x:0,y:0};addEventListener("pointermove",e=>{pointer.x=(e.clientX-innerWidth/2)/innerWidth;pointer.y=(e.clientY-innerHeight/2)/innerHeight;const m=$("#model");if(m){m.style.transform='translate3d('+(-pointer.x*28)+'px,'+(-pointer.y*18)+'px,0) rotateY('+(-pointer.x*2.2)+'deg) rotateX('+(pointer.y*1.4)+'deg)'}});addEventListener("scroll",()=>{const m=$("#model");const hero=document.querySelector(".hero");if(!m||!hero)return;const p=Math.min(1,Math.max(0,scrollY/(hero.offsetHeight*.9)));m.style.opacity=String(1-p);m.style.transform='translate3d('+(-pointer.x*28)+'px,'+(-pointer.y*18-p*140)+'px,'+(-p*220)+'px) scale('+(1-p*.42)+') rotateY('+(-pointer.x*2.2)+'deg)';});
Promise.all([fetch("/api/products").then(r=>r.json()),loadReviews()]).then(async ([products])=>{if(Array.isArray(products)){state.products=products;renderProducts();renderCart()}document.body.classList.add("ready")}).catch(()=>document.body.classList.add("ready"));
